[maestro] manually adjusting versions for .NET 7 (#434)
* [maestro] manually adjusting versions for .NET 7

We tried triggering subscriptions, such as:

    darc trigger-subscriptions --source-repo https://github.com/xamarin/xamarin-android --target-repo https://github.com/dotnet/Microsoft.Maui.Graphics --target-branch net7.0 --verbose

But then no PR opens?

So then I checked the build at:

https://maestro-prod.westus2.cloudapp.azure.com/2237/https:%2F%2Fgithub.com%2Fxamarin%2Fxamarin-android/latest/graph

Using the build id:

    darc update-dependencies --id 136370 --verbose

We get the error:

    fail: Microsoft.DotNet.Darc.Operations.Operation[0]
    Non-continuable HTTP 401 error encountered while making request
    System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
    at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 97
    fail: Microsoft.DotNet.Darc.Operations.Operation[0]
    Something failed while trying the fetch the dependencies of repo 'https://dev.azure.com/dnceng/internal/_git/dotnet-optimization'

Trial and error, I found removing this element in
`Version.Details.xml` solved it:

    <Dependency Name="Microsoft.NET.Workload.Emscripten.Manifest-6.0.300" Version="6.0.4" CoherentParentDependency="Microsoft.NETCore.App.Ref">

I switched to `Microsoft.NET.Workload.Emscripten.Manifest-7.0.100`
that xamarin-android is using here:

https://github.com/xamarin/xamarin-android/blob/6568f901a5b1a3829d8d5a5254eddd62a1765b95/eng/Version.Details.xml#L15-L18

And then things worked! I think Maestro updates will start working
after this goes in.

I also updated the `CoherentParentDependency` on:

    <Dependency Name="Microsoft.NETCore.App.Ref" Version="7.0.0-preview.5.22258.4" CoherentParentDependency="Microsoft.Dotnet.Sdk.Internal">

To match what xamarin-android has.

* Update azure-pipelines.yml

* Missed a MicrosoftNETWorkloadEmscriptenManifest60300PackageVersion

* DotNetVersionBand is 7.0.100

* DotNetMaciOSManifestVersionBand 6.0.300?

* 'dotnet workload install' now completes

* net7.0-android32.0

* Update xamarin-macios packages

darc update-dependencies --id 136557 --verbose

* net7.0-ios, macos, maccatalyst

* DotNetMaciOSManifestVersionBand contains -preview.4

* Everything NET 7.0, remove Tizen for now

* Use ./bin/dotnet/dotnet to build?

* Use DotNet.csproj to provision everything

* dotnet-local-workloads -> dotnet

* It's `dotnet build`!

* Specifically provision API 32

* Update provision.yml

* Revert "Update provision.yml"

This reverts commit adf8319346aaabebd1825af394a24f003478c0c3.

* Revert "Specifically provision API 32"

This reverts commit 83caab9397327456d82849506c20ccc09e25c3d5.

* Call sdkmanager directly

* print out files

* Use cmdline-tools\5.0\bin\sdkmanager

* Newer .NET 7 xamarin-macios builds

* Use MSBuild instead of dotnet build

* Fix Join-Path call

* More env vars

* darc update-dependencies --id 137018

* Update Versions.props

* Updated Android build

darc update-dependencies --id 137060

* Update Android/iOS version bands

* Delete the correct folders in sdk-manifests

We should delete 7.0.100 entirely

* Revert "More env vars"

This reverts commit 09efeb487d9e80bde5cefda13c60ad4b0d6b2b63.

* Revert "Fix Join-Path call"

This reverts commit 4fe5169049c016b1318585aa1448033eba3ab128.

* Revert "Use MSBuild instead of dotnet build"

This reverts commit 1c161fa72633df5ffcbd28142dfeca51b205374f.

* Update Microsoft.Maui.Graphics.Win2D.WinUI.Desktop-net6.csproj

* build windows on dotnet CLI

* :(

* Use a variable for the net7.0 part

* wrong var

* arrgh

Co-authored-by: Matthew Leibowitz <mattleibow@live.com>